DROP PROCEDURE IF EXISTS SP_ATUALIZAR_TELEFONE;
DELIMITER $$
CREATE PROCEDURE SP_ATUALIZAR_TELEFONE(IN CODIGO_TELEFONE INT, TIPO_TELEFONE ENUM ('CEL', 'RES', 'COM'), NUMERO_TELEFONE VARCHAR(20),
										ID_FORNECEDOR INT, ID_CLIENTE INT)
BEGIN
	UPDATE TELEFONE
	SET TIPO_TELEFONE = TIPO_TELEFONE, NUMERO_TELEFONE = NUMERO_TELEFONE, ID_FORNECEDOR = ID_FORNECEDOR, ID_CLIENTE = ID_CLIENTE
	WHERE IDTELEFONE = CODIGO_TELEFONE;
END $$
DELIMITER ;
