DELIMITER $$
CREATE PROCEDURE SP_INSERIR_CATEGORIA(IN 
	NOME_DA_CATEGORIA VARCHAR(50))
BEGIN
	IF EXISTS (SELECT NOME_CATEGORIA FROM CATEGORIA WHERE NOME_CATEGORIA = NOME_DA_CATEGORIA)
	THEN 
		SELECT 'CATEGORIA JÁ POSSUI CADASTRO NO SISTEMA';
	ELSE
		INSERT INTO CATEGORIA VALUES (NULL, NOME_DA_CATEGORIA);
		SELECT "CATEGORIA CADASTRADA COM SUCESSO";
	END IF;
END $$
DELIMITER ;

call distribuidora.SP_INSERIR_CATEGORIA('CACHAÇAS');