DELIMITER $$
CREATE PROCEDURE SP_INSERIR_CONTASAPAGAR(IN 
	CODIGO_DE_BARRAS VARCHAR(50),
	CLASSIFICACAO VARCHAR(45),
	DESCRICAO VARCHAR(45),
	BENEFICIARIO VARCHAR(45),
	EMISSAO DATE,
	VENCIMENTO DATE,
	VALORTOTAL DECIMAL(10,2),
	ID_FORNECEDOR INT)
BEGIN
	IF EXISTS (SELECT CODIGO_BARRAS FROM CONTASAPAGAR WHERE CODIGO_BARRAS = CODIGO_DE_BARRAS)
	THEN 
		SELECT 'CONTA JÁ CADASTRADA NO SISTEMA';
	ELSE
		INSERT INTO CONTASAPAGAR VALUES (NULL, CODIGO_DE_BARRAS, CLASSIFICACAO, 
		DESCRICAO, BENEFICIARIO, EMISSAO, VENCIMENTO, VALORTOTAL, ID_FORNECEDOR);
		SELECT "CONTA CADASTRADA COM SUCESSO";
	END IF;
END $$
DELIMITER ;

call distribuidora.SP_INSERIR_CONTASAPAGAR('7532159846321000145896321', 'MERCADORIA PARA REVENDA', 'BEBIDAS', 'BRASBEL', '2021-06-03', '2021-06-25', 1580.46, 4);
