DELIMITER $$
CREATE PROCEDURE SP_INSERIR_ENDERECO(IN 
	LOGRADOURO VARCHAR(100),
	NUMERO INT,
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(45),
	CIDADE VARCHAR(45),
	CEP VARCHAR(20),
	ID_FORNECEDOR INT,
	ID_CLIENTE INT)
BEGIN
	INSERT INTO ENDERECO VALUES (NULL, LOGRADOURO, NUMERO, 
	COMPLEMENTO, BAIRRO, CIDADE, CEP, ID_FORNECEDOR, ID_CLIENTE);
	SELECT "ENDEREÇO CADASTRADO COM SUCESSO";
END $$
DELIMITER ;

call distribuidora.SP_INSERIR_ENDERECO('QUADRA 185', 16, 'LOJA', 'RECANTO DAS EMAS', 'BRASÍLIA', '72958741', 11, NULL);
call distribuidora.SP_INSERIR_ENDERECO('QUADRA 15', 80, 'LOTE', 'CENTRO', 'SANTO ANTÔNIO DO DESCOBRETO', '72852596', NULL, 16);
