DELIMITER $$
CREATE PROCEDURE SP_INSERIR_TIPOPAGAMENTO(IN 
	TIPO_DE_PAGAMENTO ENUM ('DINHEIRO' , 'DEBITO', 'CREDITO', 'PIX'))
BEGIN
	IF EXISTS (SELECT TIPO_PAGAMENTO FROM TIPOPAGAMENTO WHERE TIPO_PAGAMENTO = TIPO_DE_PAGAMENTO)
    THEN
		SELECT "TIPO DE PAGAMENTO JÁ CADASTRADO NO SISTEMA";
	ELSE
		INSERT INTO TIPOPAGAMENTO VALUES (NULL, TIPO_DE_PAGAMENTO);
		SELECT "TIPO DE PAGAMENTO CADASTRADO COM SUCESSO";
	END IF ;
END $$
DELIMITER ;

call distribuidora.SP_INSERIR_TIPOPAGAMENTO('PIX');