#DROP PROCEDURE IF EXISTS SP_INSERIR_PEDIDO;
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_PEDIDO (IN ID_CLIENTE INT, DATA_EMISSAO DATETIME, DATA_ENTREGA DATE, ID_PRODUTO INT, 
QUANTIDADE INT, ID_TIPOPAGAMENTO INT, DATA_PAGAMENTO DATE)
BEGIN
    DECLARE VLR_VENDA DECIMAL(10,2);
	DECLARE VLR_TOTAL DECIMAL(10,2);
    
    SELECT VALOR_VENDA
    INTO VLR_VENDA
    FROM `distribuidora`.`PRODUTO`
    WHERE IDPRODUTO = ID_PRODUTO;

    SET VLR_TOTAL = QUANTIDADE * VLR_VENDA;
	
    INSERT INTO pedido VALUES (NULL, ID_CLIENTE, DATA_EMISSAO, DATA_ENTREGA, ID_PRODUTO, QUANTIDADE, VLR_TOTAL, ID_TIPOPAGAMENTO, DATA_PAGAMENTO);

	SELECT "PEDIDO REGISTRADO COM SUCESSO";
END $$
DELIMITER ;

CALL distribuidora.SP_INSERIR_PEDIDO (1, NOW(), '20210621', 5, 50, 3, '20210621');