DELIMITER $$
CREATE PROCEDURE SP_INSERIR_PRODUTO(IN 
	NOME_DO_PRODUTO VARCHAR(50),
	VALOR_CUSTO DECIMAL(10,2),
	VALOR_VENDA DECIMAL(10,2),
	QUANTIDADE INT,
	ID_CATEGORIA INT,
	ID_FORNECEDOR INT)
BEGIN
	IF EXISTS (SELECT NOME_PRODUTO FROM PRODUTO WHERE NOME_PRODUTO = NOME_DO_PRODUTO)
	THEN 
		SELECT 'PRODUTO JÁ POSSUI CADASTRO NO SISTEMA';
	ELSE
		INSERT INTO PRODUTO VALUES (NULL, NOME_DO_PRODUTO, VALOR_CUSTO, VALOR_VENDA, QUANTIDADE, ID_CATEGORIA, ID_FORNECEDOR);
		SELECT "PRODUTO CADASTRADO COM SUCESSO";
	END IF;
END $$
DELIMITER ;

call distribuidora.SP_INSERIR_PRODUTO('REF. GUARANÁ ANT. 2L', 4.41, 7.00, 5, 9, 4);