DELIMITER $$
CREATE PROCEDURE SP_INSERIR_TELEFONE(IN 
	TIPO_TELEFONE ENUM ('CEL', 'RES', 'COM'),
	NUMERO_DO_TELEFONE VARCHAR(20),
	ID_FORNECEDOR INT,
	ID_CLIENTE INT)
BEGIN
	IF EXISTS (SELECT NUMERO_TELEFONE FROM TELEFONE WHERE NUMERO_TELEFONE = NUMERO_DO_TELEFONE)
    THEN
		SELECT "TELEFONE JÁ CADASTRADO NO SISTEMA";
	ELSE
		INSERT INTO TELEFONE VALUES (NULL, TIPO_TELEFONE, NUMERO_DO_TELEFONE, ID_FORNECEDOR, ID_CLIENTE);
		SELECT "TELEFONE CADASTRADO COM SUCESSO";
	END IF ;
END $$
DELIMITER ;

call distribuidora.SP_INSERIR_TELEFONE('COM', '(61)3626-2563', 11, NULL);
call distribuidora.SP_INSERIR_TELEFONE('CEL', '(61)92589-2563', NULL, 1);