/*APAGANDO O BANCO CASO EXISTA*/
DROP DATABASE IF EXISTS DISTRIBUIDORA;

/*CRIANDO O BANCO DE DADOS, CASO NÃO EXISTA*/
CREATE DATABASE IF NOT EXISTS DISTRIBUIDORA;

/*CONECTANDO-SE AO BANCO*/
USE DISTRIBUIDORA;

/*CRIANDO AS TABELAS DO BANCO*/
CREATE TABLE IF NOT EXISTS FORNECEDOR(
	IDFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
	RAZAO_SOCIAL VARCHAR(100) NOT NULL UNIQUE,
	NOME_FANTASIA VARCHAR(50) NOT NULL UNIQUE,
	CNPJ VARCHAR(20) NOT NULL UNIQUE,
	EMAIL_FORNECEDOR VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME_CLIENTE VARCHAR(50) NOT NULL,
	CPF VARCHAR(20) NOT NULL UNIQUE,
	SEXO ENUM ('M', 'F') NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	EMAIL_CLIENTE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
	NOME_CATEGORIA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(50) NOT NULL UNIQUE,
	VALOR_CUSTO DECIMAL(10,2) NOT NULL,
	VALOR_VENDA DECIMAL(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,
	ID_CATEGORIA INT,
	ID_FORNECEDOR INT
);

CREATE TABLE IF NOT EXISTS CONTASAPAGAR(
	IDCONTASAPAGAR INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_BARRAS VARCHAR(50) NOT NULL UNIQUE,
	CLASSIFICACAO VARCHAR(45) NOT NULL,
	DESCRICAO VARCHAR(45) NOT NULL,
	BENEFICIARIO VARCHAR(45) NOT NULL,
	EMISSAO DATE NOT NULL,
	VENCIMENTO DATE NOT NULL,
	VALORTOTAL DECIMAL(10,2) NOT NULL,
	ID_FORNECEDOR INT
);

CREATE TABLE IF NOT EXISTS ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	LOGRADOURO VARCHAR(100) NOT NULL,
	NUMERO INT NOT NULL,
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(45) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	CEP VARCHAR(20),
	ID_FORNECEDOR INT,
	ID_CLIENTE INT
);

CREATE TABLE IF NOT EXISTS TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO_TELEFONE ENUM ('CEL', 'RES', 'COM') NOT NULL,
	NUMERO_TELEFONE VARCHAR(20) NOT NULL,
	ID_FORNECEDOR INT,
	ID_CLIENTE INT
);

CREATE TABLE IF NOT EXISTS TIPOPAGAMENTO(
	IDTIPOPAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO_PAGAMENTO ENUM ('DINHEIRO' , 'DEBITO', 'CREDITO', 'PIX')
);

CREATE TABLE IF NOT EXISTS PEDIDO (
	IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL,
	DATA_EMISSAO DATETIME,
	DATA_ENTREGA DATE,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR_TOTAL DECIMAL (10,2),
	ID_TIPOPAGAMENTO INT NOT NULL,
    DATA_PAGAMENTO DATE
);

/*CONSULTANDO AS TABELAS EXISTENTES NO BANCO*/
SHOW TABLES;


/*ADICIONANDO CONSTRAINTS*/
ALTER TABLE PRODUTO ADD CONSTRAINT FK_CATEGORIA_PRODUTO
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PRODUTO ADD CONSTRAINT FK_FORNECEDOR_PRODUTO
FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CONTASAPAGAR ADD CONSTRAINT FK_FORNECEDOR_CONTASAPAGAR
FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_FORNECEDOR_ENDERECO
FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_FORNECEDOR_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
ON DELETE CASCADE ON UPDATE CASCADE;
    
ALTER TABLE TELEFONE ADD CONSTRAINT FK_FORNECEDOR_TELEFONE
FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PEDIDO ADD CONSTRAINT FK_CLIENTE_PEDIDO
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PRODUTO_PEDIDO
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PEDIDO ADD CONSTRAINT FK_TIPOPAGAMENTO_PEDIDO
FOREIGN KEY (ID_TIPOPAGAMENTO) REFERENCES TIPOPAGAMENTO(IDTIPOPAGAMENTO)
ON DELETE CASCADE ON UPDATE CASCADE;