/*CRIANDO UMA FUNCTION*/
DELIMITER $$
CREATE FUNCTION FNC_ENDERECO (ID_ENDERECO INT)
RETURNS VARCHAR(150)
READS SQL DATA
BEGIN
	DECLARE END_LOGRADOURO VARCHAR(30);
	DECLARE END_NUMERO INT;
	DECLARE END_COMPLEMENTO VARCHAR (20);
	DECLARE END_BAIRRO VARCHAR (45);
	DECLARE END_CIDADE VARCHAR (45);
	DECLARE END_CEP VARCHAR (20);
	DECLARE END_ID_FORNECEDOR INT;
	DECLARE END_ID_CLIENTE INT;

	IF (SELECT ID_FORNECEDOR FROM ENDERECO WHERE IDENDERECO = ID_ENDERECO) > 0
	THEN
		SELECT LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, CEP, ID_FORNECEDOR
		INTO END_LOGRADOURO, END_NUMERO, END_COMPLEMENTO, END_BAIRRO, END_CIDADE, END_CEP, END_ID_FORNECEDOR
		FROM ENDERECO
		WHERE IDENDERECO = ID_ENDERECO;
		RETURN CONCAT(END_LOGRADOURO, ' ENDEREÇO DO FORNECEDOR', ' ' , END_NUMERO, ' ', END_COMPLEMENTO, ' ', END_BAIRRO,
					  ' ', END_CIDADE, ' ', END_CEP, ' ', END_ID_FORNECEDOR);

	ELSE
		SELECT LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, CEP, ID_CLIENTE
		INTO END_LOGRADOURO, END_NUMERO, END_COMPLEMENTO, END_BAIRRO, END_CIDADE, END_CEP, END_ID_CLIENTE
		FROM ENDERECO
		WHERE IDENDERECO = ID_ENDERECO;
		RETURN CONCAT(END_LOGRADOURO, 'ENDEREÇO DO Cliente', ' ' , END_NUMERO, ' ', END_COMPLEMENTO, ' ', END_BAIRRO,
					  ' ', END_CIDADE, ' ', END_CEP, ' ', END_ID_CLIENTE);
	END IF;
END $$
DELIMITER ;
