DROP TRIGGER IF EXISTS TG_BKP_CONTASAPAGAR;
DELIMITER $$
CREATE TRIGGER TG_BKP_CONTASAPAGAR
AFTER INSERT ON CONTASAPAGAR
FOR EACH ROW
BEGIN
	INSERT INTO BKP_DISTRIBUIDORA.BKP_CONTASAPAGAR VALUES (NULL, NEW.CODIGO_BARRAS, NEW.CLASSIFICACAO, 
				NEW.DESCRICAO, NEW.BENEFICIARIO, NEW.EMISSAO, NEW.VENCIMENTO,
				NEW.VALORTOTAL, NEW.ID_FORNECEDOR);
END $$
DELIMITER ;