/*APAGANDO O BANCO CASO EXISTA*/
DROP DATABASE IF EXISTS BKP_DISTRIBUIDORA;

/*CRIANDO O BANCO DE DADOS, CASO NÃO EXISTA*/
CREATE DATABASE IF NOT EXISTS BKP_DISTRIBUIDORA;

/*CONECTANDO-SE AO BANCO*/
USE BKP_DISTRIBUIDORA;

/*CRIANDO AS TABELAS DO BANCO*/
CREATE TABLE IF NOT EXISTS BKP_FORNECEDOR(
	IDFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
	RAZAO_SOCIAL VARCHAR(100) NOT NULL UNIQUE,
	NOME_FANTASIA VARCHAR(50) NOT NULL UNIQUE,
	CNPJ VARCHAR(20) NOT NULL UNIQUE,
	EMAIL_FORNECEDOR VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS BKP_CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME_CLIENTE VARCHAR(50) NOT NULL,
	CPF VARCHAR(20) NOT NULL UNIQUE,
	SEXO ENUM ('M', 'F') NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	EMAIL_CLIENTE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS BKP_CATEGORIA(
	IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
	NOME_CATEGORIA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS BKP_PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(50) NOT NULL UNIQUE,
	VALOR_CUSTO DECIMAL(10,2) NOT NULL,
	VALOR_VENDA DECIMAL(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,
	ID_CATEGORIA INT,
	ID_FORNECEDOR INT
);

CREATE TABLE IF NOT EXISTS BKP_CONTASAPAGAR(
	IDCONTASAPAGAR INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_BARRAS VARCHAR(50) NOT NULL UNIQUE,
	CLASSIFICACAO VARCHAR(45) NOT NULL,
	DESCRICAO VARCHAR(45) NOT NULL,
	BENEFICIARIO VARCHAR(45) NOT NULL,
	EMISSAO DATE NOT NULL,
	VENCIMENTO DATE NOT NULL,
	VALORTOTAL DECIMAL(10,2) NOT NULL,
	ID_FORNECEDOR INT
);

CREATE TABLE IF NOT EXISTS BKP_ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	LOGRADOURO VARCHAR(100) NOT NULL,
	NUMERO INT NOT NULL,
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(45) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	CEP VARCHAR(20),
	ID_FORNECEDOR INT,
	ID_CLIENTE INT
);

CREATE TABLE IF NOT EXISTS BKP_TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO_TELEFONE ENUM ('CEL', 'RES', 'COM') NOT NULL,
	NUMERO_TELEFONE VARCHAR(20) NOT NULL,
	ID_FORNECEDOR INT,
	ID_CLIENTE INT
);

CREATE TABLE IF NOT EXISTS BKP_TIPOPAGAMENTO(
	IDTIPOPAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO_PAGAMENTO ENUM ('DINHEIRO' , 'DEBITO', 'CREDITO', 'PIX')
);

CREATE TABLE IF NOT EXISTS BKP_PEDIDO (
	IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT NOT NULL,
	DATA_EMISSAO DATETIME,
	DATA_ENTREGA DATE,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR_TOTAL DECIMAL (10,2),
	ID_TIPOPAGAMENTO INT NOT NULL,
    DATA_PAGAMENTO DATE
);