DROP TRIGGER IF EXISTS TG_BKP_TIPOPAGAMENTO;
DELIMITER $$
CREATE TRIGGER TG_BKP_TIPOPAGAMENTO
AFTER INSERT ON TIPOPAGAMENTO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_DISTRIBUIDORA.BKP_TIPOPAGAMENTO SET TIPO_PAGAMENTO = NEW.TIPO_PAGAMENTO;
END $$
DELIMITER ;
