DROP TRIGGER IF EXISTS TG_BKP_PEDIDO;
DELIMITER $$
CREATE TRIGGER TG_BKP_PEDIDO
AFTER INSERT ON PEDIDO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_DISTRIBUIDORA.BKP_PEDIDO SET ID_CLIENTE = NEW.ID_CLIENTE, DATA_EMISSAO = NEW.DATA_EMISSAO, DATA_ENTREGA = NEW.DATA_ENTREGA,
				ID_PRODUTO = NEW.ID_PRODUTO, QUANTIDADE = NEW.QUANTIDADE, VALOR_TOTAL = NEW.VALOR_TOTAL, ID_TIPOPAGAMENTO = NEW.ID_TIPOPAGAMENTO,
				DATA_PAGAMENTO = NEW.DATA_PAGAMENTO;
END $$
DELIMITER ;