DROP TRIGGER IF EXISTS TG_BKP_ENDERECO;
DELIMITER $$
CREATE TRIGGER TG_BKP_ENDERECO
AFTER INSERT ON ENDERECO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_DISTRIBUIDORA.BKP_ENDERECO VALUES (NULL, NEW.LOGRADOURO, NEW.NUMERO, NEW.COMPLEMENTO,
	NEW.BAIRRO, NEW.CIDADE, NEW.CEP, NEW.ID_FORNECEDOR, NEW.ID_CLIENTE);
END $$
DELIMITER ;